"""initial schema

Revision ID: 9559d31cc403
Revises: 
Create Date: 2026-07-02 06:12:15.665004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9559d31cc403'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_uid', sa.String(length=64), nullable=False),
    sa.Column('hostname', sa.String(length=128), nullable=False),
    sa.Column('os_info', sa.String(length=256), nullable=False),
    sa.Column('device_type', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_device_uid'), 'devices', ['device_uid'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('alert_ids', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_device_id'), 'incidents', ['device_id'], unique=False)
    op.create_table('metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cpu_percent', sa.Float(), nullable=False),
    sa.Column('cpu_freq_mhz', sa.Float(), nullable=False),
    sa.Column('cpu_core_count', sa.Integer(), nullable=False),
    sa.Column('load_avg_1m', sa.Float(), nullable=False),
    sa.Column('memory_percent', sa.Float(), nullable=False),
    sa.Column('memory_used_mb', sa.Float(), nullable=False),
    sa.Column('memory_total_mb', sa.Float(), nullable=False),
    sa.Column('swap_percent', sa.Float(), nullable=False),
    sa.Column('disk_percent', sa.Float(), nullable=False),
    sa.Column('disk_used_gb', sa.Float(), nullable=False),
    sa.Column('disk_total_gb', sa.Float(), nullable=False),
    sa.Column('disk_read_mb_s', sa.Float(), nullable=False),
    sa.Column('disk_write_mb_s', sa.Float(), nullable=False),
    sa.Column('net_sent_mb_s', sa.Float(), nullable=False),
    sa.Column('net_recv_mb_s', sa.Float(), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=False),
    sa.Column('gpu_percent', sa.Float(), nullable=False),
    sa.Column('gpu_memory_percent', sa.Float(), nullable=False),
    sa.Column('battery_percent', sa.Float(), nullable=False),
    sa.Column('battery_plugged', sa.Boolean(), nullable=False),
    sa.Column('uptime_seconds', sa.Float(), nullable=False),
    sa.Column('process_count', sa.Integer(), nullable=False),
    sa.Column('top_processes', sa.JSON(), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metrics_device_id'), 'metrics', ['device_id'], unique=False)
    op.create_index(op.f('ix_metrics_timestamp'), 'metrics', ['timestamp'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('metric_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('is_anomaly', sa.Boolean(), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=False),
    sa.Column('predicted_issue', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('explanation', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['metric_id'], ['metrics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_device_id'), 'predictions', ['device_id'], unique=False)
    op.create_index(op.f('ix_predictions_metric_id'), 'predictions', ['metric_id'], unique=False)
    op.create_index(op.f('ix_predictions_timestamp'), 'predictions', ['timestamp'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('metric_id', sa.Integer(), nullable=True),
    sa.Column('prediction_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['metric_id'], ['metrics.id'], ),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_device_id'), 'alerts', ['device_id'], unique=False)
    op.create_index(op.f('ix_alerts_timestamp'), 'alerts', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_timestamp'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_device_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_predictions_timestamp'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_metric_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_device_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_metrics_timestamp'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_device_id'), table_name='metrics')
    op.drop_table('metrics')
    op.drop_index(op.f('ix_incidents_device_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_devices_device_uid'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
